import { chromium } from "/usr/lib/node_modules/@playwright/mcp/node_modules/playwright-core/index.mjs";
const b = await chromium.launch({ headless: true, executablePath: "/home/user/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome", args: ["--no-sandbox"] });
const p = await b.newPage();
const errs = []; p.on("pageerror", e => errs.push("pageerror: " + e.message)); p.on("console", m => { if (m.type() === "error") errs.push("console: " + m.text()); });
p.on("response", r => { if (r.status() >= 400) errs.push(`http ${r.status()} ${r.url()}`); });
await p.goto("https://glitchlock.hq.ripostelabs.xyz/", { waitUntil: "networkidle" });
console.log("title:", await p.title());
await p.click("#useSample");
await p.waitForSelector("#doPrepare:not([disabled])", { timeout: 120000 });
await p.click("#doPrepare");
await p.waitForSelector("#doLock:not([disabled])", { timeout: 180000 });
console.log("prepOut:", (await p.textContent("#prepOut")).replace(/\s+/g, " ").slice(0, 160));
await p.fill("#pass", "correct horse");
await p.click("#doLock");
await p.waitForSelector("#handoff", { state: "visible", timeout: 300000 });
console.log("lockOut:", (await p.textContent("#lockOut")).replace(/\s+/g, " ").slice(0, 220));
await p.click("#handoff");
await p.waitForSelector("#doUnlock:not([disabled])", { timeout: 30000 });
const pre = (await p.inputValue("#manText")).length; console.log("manifest chars in unlock box:", pre);
const passU = await p.inputValue("#passU"); console.log("unlock passphrase prefilled:", passU.length > 0);
if (!passU) await p.fill("#passU", "correct horse");
await p.click("#doUnlock");
await p.waitForSelector("#unlockOut .verdict", { timeout: 300000 });
const verdict = (await p.textContent("#unlockOut .v-h")).trim(); console.log("verdict:", verdict);
// wrong passphrase
await p.fill("#passU", "nope"); await p.click("#doUnlock");
await p.waitForFunction(() => /wrong key/i.test(document.querySelector("#unlockMsg").textContent), null, { timeout: 120000 });
console.log("wrong key text:", (await p.textContent("#unlockMsg")).replace(/\s+/g, " ").slice(0, 160));
await p.screenshot({ path: "/tmp/glitchlock-ui.png", fullPage: true });
console.log("errors:", errs.length ? errs : "none");
console.log("RESULT", /Byte-exact/.test(verdict) ? "PASS" : "FAIL");
await b.close();
